'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowDownToLine, ArrowUpRight, Briefcase, Check, ChevronDown, FileText, GraduationCap, Plus, Sparkles, Trash2, UserRound } from 'lucide-react';
import api from '@/lib/api';
import { errorMessage, Message, PageTitle, State } from './shared';

type Experience = { role: string; company: string; location: string; start_date: string; end_date: string; present: boolean; bullets: string[] };
type Education = { degree: string; school: string; location: string; graduation_date: string; details: string };
type Resume = { full_name: string; headline: string; email: string; phone: string; location: string; website: string; linkedin: string; summary: string; skills: string[]; experience: Experience[]; education: Education[]; languages: string[]; saved?: boolean };
const blankExperience = (): Experience => ({ role: '', company: '', location: '', start_date: '', end_date: '', present: false, bullets: [] });
const blankEducation = (): Education => ({ degree: '', school: '', location: '', graduation_date: '', details: '' });
const emptyResume: Resume = { full_name: '', headline: '', email: '', phone: '', location: '', website: '', linkedin: '', summary: '', skills: [], experience: [], education: [], languages: [] };
const sections = [
  { id: 'personal', label: 'Personal details', icon: UserRound, hint: 'How employers can reach you' },
  { id: 'summary', label: 'Professional summary', icon: Sparkles, hint: 'A short, honest introduction' },
  { id: 'experience', label: 'Work experience', icon: Briefcase, hint: 'Your roles and outcomes' },
  { id: 'education', label: 'Education', icon: GraduationCap, hint: 'Study and training' },
  { id: 'skills', label: 'Skills & languages', icon: Check, hint: 'What you can demonstrate' },
] as const;

function escapeHtml(value: string) { return value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character] || character)); }

function downloadResume(data: Resume) {
  const lines = (items: string[]) => items.filter(Boolean).map(item => `<li>${escapeHtml(item)}</li>`).join('');
  const experiences = data.experience.filter(item => item.role || item.company).map(item => `<article><div class="row"><strong>${escapeHtml(item.role)}</strong><span>${escapeHtml([item.start_date, item.present ? 'Present' : item.end_date].filter(Boolean).join(' — '))}</span></div><div class="muted">${escapeHtml([item.company, item.location].filter(Boolean).join(' · '))}</div><ul>${lines(item.bullets)}</ul></article>`).join('');
  const education = data.education.filter(item => item.degree || item.school).map(item => `<article><div class="row"><strong>${escapeHtml(item.degree)}</strong><span>${escapeHtml(item.graduation_date)}</span></div><div class="muted">${escapeHtml([item.school, item.location].filter(Boolean).join(' · '))}</div>${item.details ? `<p>${escapeHtml(item.details)}</p>` : ''}</article>`).join('');
  const contact = [data.email, data.phone, data.location, data.website, data.linkedin].filter(Boolean).map(escapeHtml).join(' &nbsp;·&nbsp; ');
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(data.full_name || 'Résumé')}</title><style>body{font:15px/1.55 Arial,sans-serif;color:#20232a;max-width:850px;margin:48px auto;padding:0 32px}h1{font-size:32px;margin:0;color:#183c37}h2{font-size:15px;letter-spacing:.08em;text-transform:uppercase;color:#279a80;border-bottom:1px solid #a7d6c8;padding-bottom:6px;margin-top:28px}.headline{font-size:18px;margin:4px 0 8px}.muted{color:#64716d;font-size:13px}.row{display:flex;justify-content:space-between;gap:16px}article{margin:14px 0}ul{padding-left:20px;margin:6px 0}p{margin:7px 0}@media print{body{margin:0 auto;padding:0 12mm}}</style></head><body><header><h1>${escapeHtml(data.full_name || 'Your name')}</h1><div class="headline">${escapeHtml(data.headline)}</div><div class="muted">${contact}</div></header>${data.summary ? `<section><h2>Profile</h2><p>${escapeHtml(data.summary)}</p></section>` : ''}${experiences ? `<section><h2>Experience</h2>${experiences}</section>` : ''}${education ? `<section><h2>Education</h2>${education}</section>` : ''}${data.skills.length ? `<section><h2>Skills</h2><p>${data.skills.map(escapeHtml).join(' · ')}</p></section>` : ''}${data.languages.length ? `<section><h2>Languages</h2><p>${data.languages.map(escapeHtml).join(' · ')}</p></section>` : ''}</body></html>`;
  const url = URL.createObjectURL(new Blob([html], { type: 'text/html;charset=utf-8' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${(data.full_name || 'resume').trim().replace(/[^\w-]+/g, '-')}-resume.html`; anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function ResumeBuilderPage() {
  const [data, setData] = useState<Resume>(emptyResume);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string>();
  const [openSection, setOpenSection] = useState<string>('personal');
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  useEffect(() => { api.get('/resume-builder').then(({ data: saved }) => setData({ ...emptyResume, ...saved })).catch(e => setLoadError(errorMessage(e))).finally(() => setLoading(false)); }, []);
  const complete = useMemo(() => [data.full_name, data.headline, data.email, data.summary, data.experience.some(item => item.role || item.company), data.education.some(item => item.degree || item.school), data.skills.length > 0].filter(Boolean).length, [data]);
  const update = <K extends keyof Resume>(key: K, value: Resume[K]) => setData(current => ({ ...current, [key]: value }));
  const setExperience = (index: number, patch: Partial<Experience>) => update('experience', data.experience.map((entry, i) => i === index ? { ...entry, ...patch } : entry));
  const setEducation = (index: number, patch: Partial<Education>) => update('education', data.education.map((entry, i) => i === index ? { ...entry, ...patch } : entry));
  async function save() { setSaving(true); setError(''); setMessage(''); try { const { data: saved } = await api.put('/resume-builder', data); setData({ ...emptyResume, ...saved }); setMessage('Your résumé is saved in your private workspace.'); } catch (e) { setError(errorMessage(e)); } finally { setSaving(false); } }
  const input = 'resume-field';

  if (loading || loadError) return <State loading={loading} error={loadError} retry={() => { setLoading(true); setLoadError(undefined); api.get('/resume-builder').then(({ data: saved }) => setData({ ...emptyResume, ...saved })).catch(e => setLoadError(errorMessage(e))).finally(() => setLoading(false)); }} />;

  return <div className="mx-auto max-w-[1440px]">
    <div className="flex flex-wrap items-start justify-between gap-4"><PageTitle eyebrow="Your story, clearly told" title="Résumé studio" description="Shape your experience into a résumé that sounds like you. Edit on the left and see every change on the page."/><div className="flex gap-2"><Link href="/vault" className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 hover:border-violet-200"><FileText size={15}/>My documents</Link><button onClick={() => downloadResume(data)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#1b1820] px-4 text-xs font-semibold text-white hover:bg-violet-900"><ArrowDownToLine size={15}/>Download résumé</button></div></div>
    <div className="mb-5 rounded-2xl border border-[#e9e5ed] bg-white px-4 py-3 sm:flex sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Your résumé is {complete}/7 sections ready</p><p className="mt-1 text-xs text-slate-500">Only include details you can stand behind. Nothing is published or sent to employers.</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100 sm:mt-0 sm:w-48"><div className="h-full rounded-full bg-[#58c5a1] transition-all" style={{ width: `${complete / 7 * 100}%` }}/></div></div>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(390px,.9fr)]">
      <section className="space-y-3" aria-label="Résumé editor">
        {sections.map(section => { const Icon = section.icon; const expanded = openSection === section.id; return <div key={section.id} className="overflow-hidden rounded-2xl border border-[#e9e5ed] bg-white shadow-[0_4px_20px_#25183a05]"><button type="button" onClick={() => setOpenSection(expanded ? '' : section.id)} aria-expanded={expanded} className="flex w-full items-center gap-3 px-4 py-4 text-left sm:px-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eaf7f2] text-[#22866e]"><Icon size={17}/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{section.label}</span><span className="mt-0.5 block text-xs text-slate-500">{section.hint}</span></span><ChevronDown size={17} className={`text-slate-400 transition-transform ${expanded ? 'rotate-180' : ''}`}/></button>
          {expanded && <div className="space-y-4 border-t border-slate-100 px-4 py-5 sm:px-5">
            {section.id === 'personal' && <div className="grid gap-3 sm:grid-cols-2">{([['full_name','Full name'],['headline','Professional title'],['email','Email'],['phone','Phone'],['location','City / region'],['website','Portfolio website'],['linkedin','LinkedIn profile']] as const).map(([key,label]) => <label key={key} className={`text-xs font-medium text-slate-600 ${key === 'headline' || key === 'linkedin' ? 'sm:col-span-2' : ''}`}>{label}<input className={input} value={data[key]} onChange={e => update(key, e.target.value)} maxLength={key === 'headline' ? 160 : 300} placeholder={label}/></label>)}</div>}
            {section.id === 'summary' && <><label className="block text-xs font-medium text-slate-600">A short introduction<textarea className={`${input} min-h-32 resize-y`} maxLength={3000} value={data.summary} onChange={e => update('summary', e.target.value)} placeholder="Describe your focus, strengths, and the kind of work you want. Keep it specific and true to your experience."/></label><p className="text-[11px] text-slate-400">Tip: use concrete strengths and context. Avoid claims you cannot support.</p></>}
            {section.id === 'experience' && <div className="space-y-4">{data.experience.map((item,index) => <div key={index} className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold text-slate-700">Role {index + 1}</p><button type="button" onClick={() => update('experience', data.experience.filter((_,i) => i !== index))} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-700" aria-label={`Remove role ${index + 1}`}><Trash2 size={15}/></button></div><div className="grid gap-3 sm:grid-cols-2">{([['role','Position'],['company','Company'],['location','Location'],['start_date','Start date'],['end_date','End date']] as const).map(([key,label]) => <label key={key} className="text-xs font-medium text-slate-600">{label}<input className={input} value={item[key]} onChange={e => setExperience(index,{[key]:e.target.value})}/></label>)}</div><label className="mt-3 flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={item.present} onChange={e => setExperience(index,{present:e.target.checked})}/>I currently work here</label><label className="mt-3 block text-xs font-medium text-slate-600">Highlights, one per line<textarea className={`${input} min-h-28`} value={item.bullets.join('\n')} onChange={e => setExperience(index,{bullets:e.target.value.split('\n').slice(0,12)})} placeholder="What did you do? What changed as a result?"/></label></div>)}<button type="button" onClick={() => update('experience',[...data.experience,blankExperience()])} className="inline-flex items-center gap-2 rounded-xl border border-dashed border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 hover:border-violet-300"><Plus size={15}/>Add experience</button>{!data.experience.length && <p className="text-xs text-slate-500">Start with your most recent role, project, internship, or volunteer experience.</p>}</div>}
            {section.id === 'education' && <div className="space-y-4">{data.education.map((item,index) => <div key={index} className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold text-slate-700">Education {index + 1}</p><button type="button" onClick={() => update('education',data.education.filter((_,i) => i !== index))} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-700" aria-label={`Remove education ${index + 1}`}><Trash2 size={15}/></button></div><div className="grid gap-3 sm:grid-cols-2">{([['degree','Degree / program'],['school','School'],['location','Location'],['graduation_date','Graduation date']] as const).map(([key,label])=><label key={key} className="text-xs font-medium text-slate-600">{label}<input className={input} value={item[key]} onChange={e=>setEducation(index,{[key]:e.target.value})}/></label>)}</div><label className="mt-3 block text-xs font-medium text-slate-600">Additional details<textarea className={`${input} min-h-20`} value={item.details} onChange={e=>setEducation(index,{details:e.target.value})}/></label></div>)}<button type="button" onClick={()=>update('education',[...data.education,blankEducation()])} className="inline-flex items-center gap-2 rounded-xl border border-dashed border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 hover:border-violet-300"><Plus size={15}/>Add education</button></div>}
            {section.id === 'skills' && <div className="space-y-4"><label className="block text-xs font-medium text-slate-600">Skills <span className="font-normal text-slate-400">(separate with commas)</span><textarea className={`${input} min-h-24`} value={data.skills.join(', ')} onChange={e => update('skills',e.target.value.split(',').slice(0,40).map(value=>value.trim()).filter(Boolean))} placeholder="Research, Figma, SQL, stakeholder interviews"/></label><label className="block text-xs font-medium text-slate-600">Languages <span className="font-normal text-slate-400">(separate with commas)</span><input className={input} value={data.languages.join(', ')} onChange={e => update('languages',e.target.value.split(',').slice(0,12).map(value=>value.trim()).filter(Boolean))} placeholder="English, Hindi"/></label><p className="text-[11px] leading-relaxed text-slate-500">Add skills you can discuss with examples. Self-reported skills are not certifications.</p></div>}
          </div>}
        </div>; })}
        <div className="sticky bottom-3 z-10 flex items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur"><p className="hidden text-xs text-slate-500 sm:block">Your draft stays private until you choose to share it.</p><div className="ml-auto flex items-center gap-2"><button type="button" onClick={()=>downloadResume(data)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-semibold text-slate-700 hover:bg-slate-50">Download</button><button type="button" onClick={save} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#1b1820] px-4 py-2.5 text-xs font-semibold text-white hover:bg-violet-900 disabled:opacity-60">{saving ? 'Saving…' : <><Check size={15}/>Save résumé</>}</button></div></div>
        <Message error={error} success={message}/>
      </section>
      <aside className="xl:sticky xl:top-20" aria-label="Live résumé preview"><div className="mb-2 flex items-center justify-between px-1"><div><h2 className="text-sm font-semibold">Live preview</h2><p className="mt-0.5 text-[11px] text-slate-500">Updates as you edit</p></div><span className="inline-flex items-center gap-1 rounded-full bg-[#eaf7f2] px-2.5 py-1 text-[10px] font-semibold text-[#20866d]"><span className="h-1.5 w-1.5 rounded-full bg-[#52bf9e]"/>Private draft</span></div>
        <article className="resume-preview min-h-[620px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_16px_50px_#1c19230e]"><header className="bg-[#eaf7f2] px-6 py-7 sm:px-8"><h2 className="break-words text-2xl font-semibold tracking-tight text-[#193c36]">{data.full_name || 'Your name'}</h2><p className="mt-1 text-sm font-medium text-[#318c77]">{data.headline || 'Your professional title'}</p><p className="mt-4 break-words text-[11px] leading-6 text-slate-600">{[data.email,data.phone,data.location,data.website,data.linkedin].filter(Boolean).join('  ·  ') || 'Add contact details to complete your header'}</p></header><div className="space-y-6 p-6 sm:p-8">
          {data.summary && <section><h3 className="resume-preview-heading">Profile</h3><p className="mt-3 whitespace-pre-line text-xs leading-6 text-slate-700">{data.summary}</p></section>}
          {data.experience.some(item=>item.role||item.company) && <section><h3 className="resume-preview-heading">Experience</h3><div className="space-y-5 pt-3">{data.experience.filter(item=>item.role||item.company).map((item,i)=><div key={i}><div className="flex flex-wrap justify-between gap-x-3 gap-y-1 text-xs"><strong>{item.role||'Position'}</strong><span className="text-slate-400">{[item.start_date,item.present?'Present':item.end_date].filter(Boolean).join(' — ')}</span></div><p className="mt-1 text-[11px] text-slate-500">{[item.company,item.location].filter(Boolean).join(' · ')}</p>{item.bullets.some(Boolean)&&<ul className="mt-2 list-disc space-y-1 pl-4 text-[11px] leading-5 text-slate-600">{item.bullets.filter(Boolean).map((bullet,j)=><li key={j}>{bullet}</li>)}</ul>}</div>)}</div></section>}
          {data.education.some(item=>item.degree||item.school) && <section><h3 className="resume-preview-heading">Education</h3><div className="space-y-3 pt-3">{data.education.filter(item=>item.degree||item.school).map((item,i)=><div key={i}><div className="flex justify-between gap-3 text-xs"><strong>{item.degree||'Program'}</strong><span className="text-slate-400">{item.graduation_date}</span></div><p className="mt-1 text-[11px] text-slate-500">{[item.school,item.location].filter(Boolean).join(' · ')}</p>{item.details&&<p className="mt-1 text-[11px] text-slate-600">{item.details}</p>}</div>)}</div></section>}
          {data.skills.length>0&&<section><h3 className="resume-preview-heading">Skills</h3><div className="mt-3 flex flex-wrap gap-2">{data.skills.map((skill,i)=><span key={`${skill}-${i}`} className="rounded-md bg-[#f3f6f5] px-2 py-1 text-[10px] text-slate-700">{skill}</span>)}</div></section>}
          {data.languages.length>0&&<section><h3 className="resume-preview-heading">Languages</h3><p className="mt-3 text-xs text-slate-700">{data.languages.join(' · ')}</p></section>}
          {complete<4&&<div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 p-4 text-center"><Sparkles size={17} className="mx-auto text-[#319579]"/><p className="mt-2 text-xs font-medium text-slate-700">Your story takes shape here</p><p className="mt-1 text-[11px] leading-relaxed text-slate-500">Add a summary, experience, and skills to see a fuller preview.</p></div>}
        </div><footer className="border-t border-slate-100 px-6 py-3 text-center text-[9px] text-slate-400">Edit, check, and approve every detail before you share.</footer></article>
        <Link href="/live-jobs" className="mt-3 flex items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs text-slate-600 hover:border-violet-200"><span>Looking for your next opportunity?</span><span className="inline-flex items-center gap-1 font-semibold text-violet-800">Explore jobs<ArrowUpRight size={13}/></span></Link>
      </aside>
    </div>
  </div>;
}
