'use client';
import { FormEvent, useState } from 'react';
import { useAuthContext } from '@/providers/auth-provider';
import api from '@/lib/api';
import { Empty, errorMessage, Lineage, Message, PageTitle, Panel, Role, Skill, State, Tag, useRefresh, useResource, Why } from './shared';

interface Employee { employee_id: string; name: string; role: string; skills: Record<string, number> }
interface Workforce { employees: Employee[]; coverage: Record<string, number>; concentration_risks: string[]; lineage: Lineage }
interface Curriculum { id: string; name: string; cds: number; skills: string[]; gaps: string[]; lineage: Lineage }

export function WorkforcePage() {
  const { user } = useAuthContext();
  const query = useResource<Workforce>('/organization/workforce');
  const [input, setInput] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [pending, setPending] = useState(false);
  const [skills, setSkills] = useState('python, sql'); const [exclude, setExclude] = useState(''); const [team, setTeam] = useState<{ team: Employee[]; uncovered: string[]; lineage: Lineage } | null>(null);
  const refresh = useRefresh();
  async function importCSV(e: FormEvent) {
    e.preventDefault(); setPending(true); setError('');
    try {
      const lines = input.trim().split(/\r?\n/); const header = lines.shift()?.toLowerCase().trim();
      if (header !== 'employee_id,name,role,skills') throw new Error('Use the header employee_id,name,role,skills.');
      const employees = lines.map(line => { const cells = line.split(','); if (cells.length !== 4) throw new Error('Each row needs four columns. Commas inside values are not supported.'); const [employee_id, name, role, skillText] = cells.map(x => x.trim()); const entries = skillText.split(';').filter(Boolean).map(item => { const [skill, level] = item.trim().split(':'); if (!skill || !level || !Number.isFinite(Number(level))) throw new Error('Use skill:score pairs, for example python:80;sql:70.'); return [skill, Number(level)]; }); return { employee_id, name, role, skills: Object.fromEntries(entries) }; });
      await api.post('/organization/workforce', { employees }); await refresh(); setSuccess(`${employees.length} employees saved in your workspace.`);
    } catch (e) { setError(e instanceof Error && !('isAxiosError' in e) ? e.message : errorMessage(e)); } finally { setPending(false); }
  }
  async function compose(e: FormEvent) { e.preventDefault(); setPending(true); setError(''); try { setTeam((await api.post('/organization/team', { skills: skills.split(',').map(s => s.trim()).filter(Boolean), size: 3, excluded_employees: exclude.split(',').map(s => s.trim()).filter(Boolean) })).data); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }
  if (user?.tenant_type !== 'organization') return <Empty title="An organization workspace is required" description="Workforce data and team composition are available to organization administrators."/>;
  return <div className="max-w-6xl mx-auto"><PageTitle eyebrow="People, skills, possibility" title="Know what your team can do." description="Map reported skills, spot concentration risks, and compose a team for the work ahead."/><div className="grid lg:grid-cols-2 gap-6"><Panel><h2 className="font-semibold text-lg">Import workforce data</h2><p className="text-sm text-slate-500 mt-2">Paste a simple CSV. Skill levels range from 0 to 100 and are self-reported.</p><form onSubmit={importCSV} className="mt-4 space-y-4"><label className="text-sm font-medium">Employee CSV<textarea required rows={6} className="journey-input font-mono text-xs" placeholder={'employee_id,name,role,skills\nE1,Asha,Engineer,python:80;sql:70'} value={input} onChange={e => setInput(e.target.value)}/></label><button disabled={pending} className="btn-primary">Save workforce</button></form></Panel><Panel><h2 className="font-semibold text-lg">Team composer & shock scenario</h2><form onSubmit={compose} className="mt-4 space-y-4"><label className="block text-sm font-medium">Required skill IDs<input className="journey-input" value={skills} onChange={e => setSkills(e.target.value)} required/></label><label className="block text-sm font-medium">Exclude employee IDs to simulate absence<input className="journey-input" value={exclude} onChange={e => setExclude(e.target.value)} placeholder="E1, E3"/></label><button disabled={pending} className="btn-secondary">Compose a team of up to 3</button></form>{team && <div className="mt-5 text-sm"><p className="font-medium">Suggested team: {team.team.map(e => e.name).join(', ') || 'No covering team'}</p><p className="text-slate-500 mt-2">Uncovered: {team.uncovered.join(', ') || 'None'}</p><Why lineage={team.lineage}/></div>}</Panel></div><Message error={error} success={success}/><State loading={query.isPending} error={query.error} retry={() => query.refetch()}/>{query.data && <Panel className="mt-6"><h2 className="font-semibold text-lg">{query.data.employees.length} people · skill coverage</h2><div className="flex flex-wrap gap-2 my-5">{Object.entries(query.data.coverage).map(([skill, count]) => <Tag key={skill} green={count > 1}>{skill}: {count} {count === 1 ? '· single holder' : 'people'}</Tag>)}</div><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr className="text-slate-500 border-b"><th className="py-3">Employee</th><th>Role</th><th>Reported skills</th></tr></thead><tbody>{query.data.employees.map(e => <tr key={e.employee_id} className="border-b border-slate-100"><td className="py-3 font-medium">{e.name}<span className="text-xs text-slate-400 ml-2">{e.employee_id}</span></td><td>{e.role}</td><td className="py-3">{Object.entries(e.skills).map(([s, level]) => `${s} ${level}`).join(' · ')}</td></tr>)}</tbody></table></div><Why lineage={query.data.lineage}/></Panel>}</div>;
}

export function CurriculumPage() {
  const { user } = useAuthContext(); const roles = useResource<Role[]>('/roles'); const skills = useResource<Skill[]>('/skills'); const query = useResource<Curriculum[]>('/institution/curriculum'); const refresh = useRefresh();
  const [name, setName] = useState(''); const [role, setRole] = useState('software-engineer'); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState(''); const [pending, setPending] = useState(false);
  async function analyze(e: FormEvent) { e.preventDefault(); setPending(true); setError(''); try { await api.post('/institution/curriculum', { name, role_id: role, skills: selected }); await refresh(); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }
  if (user?.tenant_type !== 'institution') return <Empty title="An institution workspace is required" description="Curriculum alignment is available to institution administrators and placement officers."/>;
  return <div className="max-w-5xl mx-auto"><PageTitle eyebrow="Connect learning to possibility" title="Build a more relevant curriculum." description="Compare the skills you teach against a demo role profile. Find gaps with an explainable curriculum drift score."/><Panel><form onSubmit={analyze} className="space-y-5"><div className="grid sm:grid-cols-2 gap-5"><label className="text-sm font-medium">Program or course name<input required maxLength={160} className="journey-input" value={name} onChange={e => setName(e.target.value)}/></label><label className="text-sm font-medium">Target role<select className="journey-input" value={role} onChange={e => setRole(e.target.value)}>{roles.data?.map(r => <option key={r.id} value={r.id}>{r.title}</option>)}</select></label></div><fieldset><legend className="text-sm font-medium mb-3">Skills covered in your curriculum</legend><div className="flex flex-wrap gap-2">{skills.data?.map(s => <label key={s.id} className={`cursor-pointer text-sm px-3 py-2 rounded-lg border ${selected.includes(s.id) ? 'bg-violet-50 border-violet-300' : 'border-slate-200'}`}><input type="checkbox" className="mr-2 accent-violet-600" checked={selected.includes(s.id)} onChange={() => setSelected(selected.includes(s.id) ? selected.filter(id => id !== s.id) : [...selected, s.id])}/>{s.name}</label>)}</div></fieldset><button className="btn-primary" disabled={pending || !selected.length}>{pending ? 'Analyzing…' : 'Analyze curriculum'}</button></form></Panel><Message error={error}/><State loading={query.isPending} error={query.error} retry={() => query.refetch()}/><div className="grid md:grid-cols-2 gap-5 mt-6">{query.data?.map(c => <Panel key={c.id}><Tag>Demo role comparison</Tag><h2 className="font-semibold text-xl mt-3">{c.name}</h2><p className="text-4xl font-semibold mt-5">{c.cds.toFixed(1)}<span className="text-lg text-slate-400">% drift</span></p><p className="text-sm text-slate-500 mt-4">Skills to consider: {c.gaps.join(', ') || 'All target skills are covered.'}</p><Why lineage={c.lineage}/></Panel>)}</div></div>;
}
